### ISSUE TITLE
Epson EB-1776W

### ISSUE THREAD

**Issue by roydebruin** [LightsOnHudson/FPP-Plugin-Projector-Control#3] opened 2018-04-25 06:43 UTC
Being new to this area I hope I am in the right place .... I am running FPP on a Raspberry Pi3 and had downloaded your Projector Plugin but can't find a direct match to my projector in your list.  There are two Powerlite Models in your list which closely resembles the projector I have.  Are either of these likely to be compatible to turn on/off the projector or do you need further details from me to answer?

**Comment by patdelaney** [comment] 2018-04-26 15:48
WHat is the model or your projector?

**Comment by roydebruin** [comment] 2018-04-26 22:03
Sorry I thought that was the EB number but the back has Model Number = H476B
		
		

		Trumagik investments P/LRoy de BruinDirectorm: +61 404057000e: roy.debruin@trumagik.com.au
	




On Fri, Apr 27, 2018 at 1:48 AM +1000, "patdelaney" <notifications@github.com> wrote:










WHat is the model or your projector?



On Wed, Apr 25, 2018 at 1:43 AM, roydebruin <notifications@github.com>

wrote:

**Comment by patdelaney** [comment] 2023-06-15 00:39
Closing the issue is 5 years old

**Comment by patdelaney** [comment] 2023-06-15 00:39
Closing the issue is 5 years old

**Comment by patdelaney** [comment] 2023-06-15 00:39
Closing the issue is 5 years old

**Closed by patdelaney** 2023-06-15 00:39 UTC
