### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by datcomputerguy** [LightsOnHudson/FPP-Plugin-Projector-Control#7] opened 2020-11-18 01:49 UTC
Can't seem to make an issue on the falcon github page for the Projector Plugin.
But there is a dependency that appears to not be installed on the latest RPi FPP image.
Going into SSH and doing this seems to fix it:
`sudo cpan Net::PJLink`
Takes a little bit, but it downloads what it needs and then the plugin works.

**Comment by patdelaney** [comment] 2020-11-19 00:16
I'm not sure I have enough information to look at this. 
Was this fresh install or upgrade?
What projector are you using?
How are you trying to connect to the projector?

**Comment by TranscendOfSypherus** [comment] 2020-12-17 08:58
This also worked for me on a fresh install of FPP 4.5 using PJLink to control power to my projector before and after the show.
Having added the FalconChristmas/FPP-Plugin-Projector-Control  plugin I was unable to control the projector however PJLinker2 on android was able to control the projector.

After finding this issue I tried the `sudo cpan Net::PJLink` command, waited for it to conclude and the plugin was working as expected.

Log output with and without the library installed is identical, no errors are logged to the FPP logs.

**Comment by patdelaney** [comment] 2023-06-15 00:39
Closing the issue is 3 years old

**Closed by patdelaney** 2023-06-15 00:39 UTC
